---
- name: Launch application container
  docker_container:
    name: my-backend-container
    image: greenway13/tp-devops-simple-api:latest
    pull: true
    networks:
      - name: private-network
      - name: front-network
    volumes:
      - /opt/application.yml:/config/application.yml:ro
    ports:
      - "8080:8080"
    restart_policy: on-failure
    restart_retries: 3
    env:
      DB_USER: "usr"
      DB_PASSWORD: "pwd"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
